### ISSUE TITLE
可以转载到公众号吗

### ISSUE THREAD

**Issue by krisjin** [zhpmatrix/nlp-competitions-list-review#6]
你好，文章很好，可以转载到公众号吗

**Comment by zhpmatrix** [comment]
@krisjin 可以转载的，但是注明我的Github地址。

**Comment by zhpmatrix** [comment]
@krisjin 你的公众号是?

**Comment by krisjin** [comment]
> @krisjin 你的公众号是?

公众号是行走的数据，注明github地址没问题哈

**Comment by krisjin** [comment]
https://zhpmatrix.github.io/ 可以以原创的方式发布吗，注明出自https://github.com/zhpmatrix

**Comment by zhpmatrix** [comment]
@krisjin 博客可以转，写博客地址和作者就可以。

**Comment by krisjin** [comment]
好勒，感谢，作者写@zhpmatrix 写这个吗

**Comment by krisjin** [comment]
@zhpmatrix  是以原创的方式发布哈，这个可以吗

**Comment by zhpmatrix** [comment]
@krisjin 可以。

**Comment by zhpmatrix** [comment]
> 好勒，感谢，作者写@zhpmatrix 写这个吗

是的。

**Comment by krisjin** [comment]
👌

**Comment by krisjin** [comment]
1881048930这是我的微信，方便的话可以加下哈

**Comment by zhpmatrix** [comment]
@krisjin 用户不存在~?

**Comment by krisjin** [comment]
18810489320这个
