### ISSUE TITLE
2019smp task1 

### ISSUE THREAD

**Issue by xiao-ming-code** [zhpmatrix/nlp-competitions-list-review#9]
SMP2019 nlu这个任务有么，结果能达到多少

**Comment by zhpmatrix** [comment]
抱歉，好久没看到。

**Comment by fhm-sxdx** [comment]
感谢您的回复




冬笙
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zhpmatrix/nlp-competitions-list-review"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月8日(星期天) 中午1:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [zhpmatrix/nlp-competitions-list-review] 2019smp task1  (#9)





 
Closed #9 as completed.
